### ISSUE TITLE
Cannot install add-on 

### ISSUE THREAD

**Issue by Bascht74** [davidusb-geek/emhass#328]
**Describe the bug**
I cannot install the add-on

**To Reproduce**
Try to install the add-on within HA '(2024-07)

**Expected behavior**
The add-on will be installed

**Screenshots**
<img width="534" alt="image" src="https://github.com/user-attachments/assets/60b29a6f-3cb3-455d-8883-da1875ec0527">

**Home Assistant installation type**
 - Home Assistant OS

**Your hardware**
- OS: HA OS
- Architecture: amd64 (Proxmox)

**EMHASS installation type**
 - Add-on

**Additional context**
./.

**Comment by eddysteurs** [comment]
same error during upgrade from 0.10.5 to 0.10.6

**Comment by davidusb-geek** [comment]
You can try no_, it should be solved

**Comment by Bascht74** [comment]
Working. Thx!

Am So., 14. Juli 2024 um 10:55 Uhr schrieb David ***@***.***>:

**Comment by poundy** [comment]
I'm still seeing this on RPi4/x86 (ARMv7?) when upgrading... 
![image](https://github.com/user-attachments/assets/35d9b353-01b3-43dc-89dd-2809da31e7ea)
